//! One API document for one route tree.
//!
//! [`contract`] merges every carrier that contributes operations; the axum
//! `Router` the service binds and the OpenAPI document written to
//! `api/openapi/service.yaml` share the same tracked construction.
//!
//! The committed YAML is generated output: `make openapi-generate` rewrites
//! it and the `openapi` integration test refuses a stale copy. Reviewers,
//! the linter, and the breaking-change comparison read the YAML; the Rust
//! annotations are where a change is made.

use std::error::Error;

use health::ReadinessReader;
use infra_http::ContractRouter;
// template:begin http-idempotency:service-api-http-idempotency-import
use infra_http::idempotency::Composer;
// template:end http-idempotency:service-api-http-idempotency-import
// template:begin authn:service-api-authn-imports
use utoipa::Modify;
use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
// template:end authn:service-api-authn-imports
use utoipa::OpenApi;
use utoipa::openapi::OpenApi as Document;

/// First line of the committed document, so a reader knows where to edit.
const GENERATED_HEADER: &str =
    "# Generated by `make openapi-generate` from the Rust contract; do not edit by hand.";

/// Document identity. `version` and `license` follow this crate's Cargo
/// metadata; the title names the service the way the repository does.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "rust-service-template-rest",
        description = "HTTP contract served by the `service` binary: platform probes and feature operations, with RFC 9457 problem responses from one closed catalog."
    ),
    servers((url = "/", description = "current service origin")),
    tags(
        (name = "system", description = "Operational endpoints for liveness and readiness."),
        // template:begin inbound-webhooks:service-api-webhooks-tag
        (name = "webhooks", description = "Authenticated inbound webhook admission.")
        // template:end inbound-webhooks:service-api-webhooks-tag
    ),
    // template:begin authn:service-api-authn-document-security
    modifiers(&BearerAuth),
    security(("bearerAuth" = []))
    // template:end authn:service-api-authn-document-security
)]
struct ApiDoc;

// template:begin authn:service-api-authn-security-scheme
struct BearerAuth;

impl Modify for BearerAuth {
    fn modify(&self, document: &mut Document) {
        document
            .components
            .get_or_insert_with(utoipa::openapi::Components::new)
            .add_security_scheme(
                "bearerAuth",
                SecurityScheme::Http(HttpBuilder::new().scheme(HttpAuthScheme::Bearer).build()),
            );
    }
}
// template:end authn:service-api-authn-security-scheme

/// Every operation the service serves, with its contract, as one
/// [`ContractRouter`] whose [`ReadinessReader`] state is still unapplied.
/// Bootstrap finalizes it, supplies the state, and hardens the routes;
/// [`document`] consumes the document-only path.
///
/// # Errors
///
/// Returns a local idempotency composition error when a participating route
/// cannot carry the required served contract.
pub fn contract(
    // template:begin http-idempotency:service-api-contract-composer
    idempotency: &mut Composer,
    // template:end http-idempotency:service-api-contract-composer
) -> Result<ContractRouter<ReadinessReader>, Box<dyn Error + Send + Sync>> {
    let contract = assemble();
    // template:begin http-idempotency:service-api-idempotency-components
    let contract = contract.merge_document(idempotency.components());
    // template:end http-idempotency:service-api-idempotency-components
    Ok(contract)
}

fn assemble() -> ContractRouter<ReadinessReader> {
    ContractRouter::with_openapi(ApiDoc::openapi())
        .merge(infra_http::router())
        // template:begin inbound-webhooks:service-api-webhooks-router
        .merge(infra_http::webhooks::router())
    // template:end inbound-webhooks:service-api-webhooks-router
}

/// The OpenAPI document of [`contract`].
///
/// # Errors
///
/// Returns a local idempotency composition error when a participating route
/// cannot carry the required served contract.
pub fn document() -> Result<Document, Box<dyn Error + Send + Sync>> {
    contract(
        // template:begin http-idempotency:service-api-document-composer
        &mut Composer::inert(),
        // template:end http-idempotency:service-api-document-composer
    )
    .map(ContractRouter::into_document)
}

/// The committed form of [`document`]: the generated-file header followed
/// by the YAML rendering, ending in one newline.
///
/// # Errors
///
/// Returns a local idempotency composition error or YAML serialization error.
pub fn render() -> Result<String, Box<dyn Error + Send + Sync>> {
    let yaml = document()?.to_yaml()?;
    Ok(format!("{GENERATED_HEADER}\n{}\n", yaml.trim_end()))
}

// template:begin authn:service-api-protected-test-route
#[cfg(test)]
mod tests {
    use axum::http::StatusCode;
    use axum::http::header::AUTHORIZATION;
    use axum::response::IntoResponse;

    use super::*;

    #[utoipa::path(
        get,
        path = "/_test/protected",
        tag = "system",
        operation_id = "testProtected",
        summary = "Test-only protected composition seam",
        security(("bearerAuth" = [])),
        extensions(("x-security-decision" = json!({
            "exposure": "protected",
            "rationale": "test-only route proving the production bearer composition seam"
        }))),
        responses(
            (status = 200, description = "verified", content_type = "text/plain", body = String),
            infra_http::problem::responses::ProtectedOperationProblemResponses,
        )
    )]
    async fn protected(
        principal: infra_http::VerifiedPrincipal,
        headers: axum::http::HeaderMap,
    ) -> impl IntoResponse {
        let authorization_was_removed = !headers.contains_key(AUTHORIZATION);
        let identity_was_verified = !principal.issuer().is_empty()
            && (principal.subject().is_some() || principal.client_id().is_some());
        if authorization_was_removed && identity_was_verified {
            (StatusCode::OK, "verified").into_response()
        } else {
            StatusCode::INTERNAL_SERVER_ERROR.into_response()
        }
    }

    fn protected_test_contract() -> ContractRouter<ReadinessReader> {
        assemble().routes(infra_http::routes!(protected))
    }

    #[test]
    fn repair_regression_protected_contract_refuses_disabled_authentication_without_a_composer() {
        assert!(
            infra_http::authn::finalize(
                protected_test_contract(),
                infra_bearerauthn::Verifier::disabled(),
                32 * 1024,
            )
            .is_err(),
            "protected operations must refuse startup when authentication is disabled"
        );
    }

    #[test]
    fn public_probe_contract_does_not_depend_on_a_verifier() {
        assert!(
            infra_http::authn::finalize(
                assemble(),
                infra_bearerauthn::Verifier::disabled(),
                32 * 1024,
            )
            .is_ok()
        );
    }
}
// template:end authn:service-api-protected-test-route
// template:begin http-idempotency:service-api-idempotent-test-route
#[cfg(test)]
mod idempotency_tests {
    use axum::http::StatusCode;
    use axum::response::Response;
    use infra_http::idempotency::{Activation, Idempotency, Tx};

    use super::*;

    #[utoipa::path(
        post,
        path = "/_test/idempotent",
        tag = "system",
        operation_id = "testIdempotent",
        summary = "Test-only idempotent composition seam",
        security(("bearerAuth" = [])),
        extensions(
            ("x-security-decision" = json!({
                "exposure": "protected",
                "rationale": "test-only route proving the production idempotency composition seam"
            }))
        ),
        responses(
            (status = 201, description = "created", content_type = "text/plain", body = String),
            infra_http::problem::responses::ProtectedOperationProblemResponses,
        )
    )]
    async fn idempotent(idempotency: Idempotency) -> Response {
        idempotency
            .execute(async |_: &mut Tx<'_>| (StatusCode::CREATED, "created"))
            .await
    }

    /// The production contract with the test route composed through the
    /// same composer.
    fn with_test_route(
        idempotency: &mut Composer,
    ) -> Result<ContractRouter<ReadinessReader>, Box<dyn Error + Send + Sync>> {
        Ok(contract(idempotency)?.routes(idempotency.route(infra_http::routes!(idempotent))?))
    }

    /// Activation counts only routes that composed successfully.
    fn finished(
        compose: impl FnOnce(
            &mut Composer,
        )
            -> Result<ContractRouter<ReadinessReader>, Box<dyn Error + Send + Sync>>,
    ) -> Activation {
        let mut composer = Composer::inert();
        let _contract = compose(&mut composer).expect("the route composes");
        composer.finish()
    }

    /// Idempotent operations the boundary serves; none while inactive.
    fn served(activation: &Activation) -> usize {
        match activation {
            Activation::Inactive => 0,
            Activation::Active { operations, .. } => operations.get(),
        }
    }

    #[test]
    fn test_only_idempotent_route_generates_the_served_contract() {
        let mut composer = Composer::inert();
        let contract = with_test_route(&mut composer).expect("test route composes");
        assert!(matches!(composer.finish(), Activation::Active { .. }));
        let document = serde_json::to_value(contract.document()).unwrap();
        let operation = &document["paths"]["/_test/idempotent"]["post"];
        assert!(operation.get("x-idempotent").is_none());
        let parameters = operation["parameters"].as_array().unwrap();
        let key = parameters
            .iter()
            .find(|parameter| parameter["name"] == "Idempotency-Key")
            .expect("composition adds the key parameter");
        assert_eq!(key["in"], "header");
        assert_eq!(key["required"], true);
        assert_eq!(key["schema"]["type"], "string");
        assert!(key["schema"].get("maxLength").is_none());
        assert!(key["schema"].get("pattern").is_none());
        for (status, component) in [
            ("400", "IdempotencyBadRequest"),
            ("401", "AuthenticationUnauthorized"),
            ("403", "AuthenticationForbidden"),
            ("409", "IdempotencyRequestInProgress"),
            ("413", "RequestEntityTooLarge"),
            ("422", "IdempotencyKeyMismatch"),
            ("500", "InternalServerError"),
            ("503", "IdempotencyUnavailable"),
        ] {
            assert_eq!(
                operation["responses"][status]["$ref"],
                format!("#/components/responses/{component}")
            );
        }
        assert_eq!(operation["responses"]["201"]["description"], "created");
        assert_eq!(
            operation["responses"]["201"]["headers"]["Idempotent-Replayed"]["schema"],
            serde_json::json!({ "type": "string", "enum": ["true"] })
        );
    }

    #[test]
    fn composing_the_test_route_adds_exactly_one_served_operation() {
        // The plain contract serves only what is composed into it: nothing,
        // so the boundary stays inactive, until an operation opts in.
        assert_eq!(
            served(&finished(contract)) + 1,
            served(&finished(with_test_route))
        );
    }
}
// template:end http-idempotency:service-api-idempotent-test-route
