//! One API document for one route tree.
//!
//! [`contract`] merges every router that contributes operations; the axum
//! `Router` the service binds and the OpenAPI document written to
//! `api/openapi/service.yaml` are the two halves of that one value, so they
//! cannot describe different services. A feature crate adds its
//! `OpenApiRouter` here and nowhere else.
//!
//! The committed YAML is generated output: `make openapi-generate` rewrites
//! it and the `openapi` integration test refuses a stale copy. Reviewers,
//! the linter, and the breaking-change comparison read the YAML; the Rust
//! annotations are where a change is made.

use std::error::Error;

use health::ReadinessReader;
use utoipa::OpenApi;
use utoipa::openapi::OpenApi as Document;
use utoipa_axum::router::OpenApiRouter;

/// First line of the committed document, so a reader knows where to edit.
const GENERATED_HEADER: &str =
    "# Generated by `make openapi-generate` from the Rust contract; do not edit by hand.";

/// Document identity. `version` and `license` follow this crate's Cargo
/// metadata; the title names the service the way the repository does.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "rust-service-template-rest",
        description = "HTTP contract served by the `service` binary: platform probes and feature operations, with RFC 9457 problem responses from one closed catalog."
    ),
    servers((url = "/", description = "current service origin")),
    tags((name = "system", description = "Operational endpoints for liveness and readiness."))
)]
struct ApiDoc;

/// Every operation the service serves, with its contract, over the shared
/// readiness reader. Bootstrap supplies the state and hardens the routes.
#[must_use]
pub fn contract() -> OpenApiRouter<ReadinessReader> {
    OpenApiRouter::with_openapi(ApiDoc::openapi()).merge(infra_http::router())
}

/// The OpenAPI document of [`contract`].
#[must_use]
pub fn document() -> Document {
    contract().split_for_parts().1
}

/// The committed form of [`document`]: the generated-file header followed
/// by the YAML rendering, ending in one newline.
///
/// # Errors
///
/// Returns the serializer's error; a type-constructed document has no
/// known way to trigger one.
pub fn render() -> Result<String, Box<dyn Error + Send + Sync>> {
    let yaml = document().to_yaml()?;
    Ok(format!("{GENERATED_HEADER}\n{}\n", yaml.trim_end()))
}
