//! One API document for one route tree.
//!
//! [`contract`] merges every carrier that contributes operations; the axum
//! `Router` the service binds and the OpenAPI document written to
//! `api/openapi/service.yaml` share the same tracked construction.
//!
//! The committed YAML is generated output: `make openapi-generate` rewrites
//! it and the `openapi` integration test refuses a stale copy. Reviewers,
//! the linter, and the breaking-change comparison read the YAML; the Rust
//! annotations are where a change is made.

use std::error::Error;

use health::ReadinessReader;
use infra_http::ContractRouter;
// template:begin http-idempotency:service-api-http-idempotency-import
use infra_http::idempotency::Composer;
// template:end http-idempotency:service-api-http-idempotency-import
// template:begin authn:service-api-authn-imports
use utoipa::Modify;
use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
// template:end authn:service-api-authn-imports
use utoipa::OpenApi;
use utoipa::openapi::OpenApi as Document;

/// First line of the committed document, so a reader knows where to edit.
const GENERATED_HEADER: &str =
    "# Generated by `make openapi-generate` from the Rust contract; do not edit by hand.";

/// Document identity. `version` and `license` follow this crate's Cargo
/// metadata; the title names the service the way the repository does.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "rust-service-template-rest",
        description = "HTTP contract served by the `service` binary: platform probes and feature operations, with RFC 9457 problem responses from one closed catalog."
    ),
    servers((url = "/", description = "current service origin")),
    tags((name = "system", description = "Operational endpoints for liveness and readiness.")),
    // template:begin authn:service-api-authn-document-security
    modifiers(&BearerAuth),
    security(("bearerAuth" = []))
    // template:end authn:service-api-authn-document-security
)]
struct ApiDoc;

// template:begin authn:service-api-authn-security-scheme
struct BearerAuth;

impl Modify for BearerAuth {
    fn modify(&self, document: &mut Document) {
        document
            .components
            .get_or_insert_with(utoipa::openapi::Components::new)
            .add_security_scheme(
                "bearerAuth",
                SecurityScheme::Http(HttpBuilder::new().scheme(HttpAuthScheme::Bearer).build()),
            );
    }
}
// template:end authn:service-api-authn-security-scheme

/// Every operation the service serves, with its contract, as one
/// [`ContractRouter`] whose [`ReadinessReader`] state is still unapplied.
/// Bootstrap finalizes it, supplies the state, and hardens the routes;
/// [`document`] consumes the document-only path.
#[must_use]
pub fn contract(
    // template:begin http-idempotency:service-api-contract-composer
    idempotency: &mut Composer,
    // template:end http-idempotency:service-api-contract-composer
) -> ContractRouter<ReadinessReader> {
    assemble()
        // template:begin http-idempotency:service-api-idempotency-components
        .merge_document(idempotency.components())
    // template:end http-idempotency:service-api-idempotency-components
}

fn assemble() -> ContractRouter<ReadinessReader> {
    ContractRouter::with_openapi(ApiDoc::openapi()).merge(infra_http::router())
}

/// The OpenAPI document of [`contract`].
#[must_use]
pub fn document() -> Document {
    contract(
        // template:begin http-idempotency:service-api-document-composer
        &mut Composer::inert(),
        // template:end http-idempotency:service-api-document-composer
    )
    .into_document()
}

/// The committed form of [`document`]: the generated-file header followed
/// by the YAML rendering, ending in one newline.
///
/// # Errors
///
/// Returns the serializer's error; a type-constructed document has no
/// known way to trigger one.
pub fn render() -> Result<String, Box<dyn Error + Send + Sync>> {
    let yaml = document().to_yaml()?;
    Ok(format!("{GENERATED_HEADER}\n{}\n", yaml.trim_end()))
}

// template:begin authn:service-api-protected-test-route
#[cfg(test)]
mod tests {
    use axum::http::StatusCode;
    use axum::http::header::AUTHORIZATION;
    use axum::response::IntoResponse;

    use super::*;

    #[utoipa::path(
        get,
        path = "/_test/protected",
        tag = "system",
        operation_id = "testProtected",
        summary = "Test-only protected composition seam",
        security(("bearerAuth" = [])),
        extensions(("x-security-decision" = json!({
            "exposure": "protected",
            "rationale": "test-only route proving the production bearer composition seam"
        }))),
        responses(
            (status = 200, description = "verified", content_type = "text/plain", body = String),
            infra_http::problem::responses::ProtectedOperationProblemResponses,
        )
    )]
    async fn protected(
        principal: infra_http::VerifiedPrincipal,
        headers: axum::http::HeaderMap,
    ) -> impl IntoResponse {
        let authorization_was_removed = !headers.contains_key(AUTHORIZATION);
        let identity_was_verified = !principal.issuer().is_empty()
            && (principal.subject().is_some() || principal.client_id().is_some());
        if authorization_was_removed && identity_was_verified {
            (StatusCode::OK, "verified").into_response()
        } else {
            StatusCode::INTERNAL_SERVER_ERROR.into_response()
        }
    }

    fn protected_test_contract() -> ContractRouter<ReadinessReader> {
        assemble().routes(infra_http::routes!(protected))
    }

    #[test]
    fn repair_regression_protected_contract_refuses_disabled_authentication_without_a_composer() {
        assert!(
            infra_http::authn::finalize(
                protected_test_contract(),
                infra_bearerauthn::Verifier::disabled(),
                32 * 1024,
            )
            .is_err(),
            "protected operations must refuse startup when authentication is disabled"
        );
    }

    #[test]
    fn public_probe_contract_does_not_depend_on_a_verifier() {
        assert!(
            infra_http::authn::finalize(
                assemble(),
                infra_bearerauthn::Verifier::disabled(),
                32 * 1024,
            )
            .is_ok()
        );
    }
}
// template:end authn:service-api-protected-test-route
// template:begin http-idempotency:service-api-idempotent-test-route
#[cfg(test)]
mod idempotency_tests {
    use std::num::NonZeroU32;

    use axum::http::StatusCode;
    use axum::response::Response;
    use infra_http::idempotency::{Activation, Fingerprint, Idempotency, Tx};

    use super::*;

    /// Version of the test operation's semantic input.
    const TEST_INPUT_V1: NonZeroU32 = NonZeroU32::MIN;

    #[utoipa::path(
        post,
        path = "/_test/idempotent",
        tag = "system",
        operation_id = "testIdempotent",
        summary = "Test-only idempotent composition seam",
        params(infra_http::idempotency::IdempotencyKey),
        security(("bearerAuth" = [])),
        extensions(
            ("x-security-decision" = json!({
                "exposure": "protected",
                "rationale": "test-only route proving the production idempotency composition seam"
            })),
            ("x-idempotent" = json!(true))
        ),
        responses(
            (status = 201, description = "created", content_type = "text/plain", body = String),
            infra_http::idempotency::IdempotentOperationProblemResponses,
        )
    )]
    async fn idempotent(idempotency: Idempotency) -> Response {
        idempotency
            .execute(
                Fingerprint::new(TEST_INPUT_V1, &()),
                async |_: &mut Tx<'_>| (StatusCode::CREATED, "created"),
            )
            .await
    }

    /// The production contract with the test route composed through the
    /// same composer.
    fn with_test_route(idempotency: &mut Composer) -> ContractRouter<ReadinessReader> {
        contract(idempotency).routes(idempotency.route(infra_http::routes!(idempotent)))
    }

    /// Agreement of the contract `compose` builds through a fresh inert
    /// composer.
    fn agreed(
        compose: impl FnOnce(&mut Composer) -> ContractRouter<ReadinessReader>,
    ) -> Activation {
        let mut composer = Composer::inert();
        let contract = compose(&mut composer);
        composer
            .agree(contract.document())
            .expect("the contract agrees with the routes composed through it")
    }

    /// Idempotent operations the boundary serves; none while inactive.
    fn served(activation: &Activation) -> usize {
        match activation {
            Activation::Inactive => 0,
            Activation::Active { operations, .. } => operations.get(),
        }
    }

    #[test]
    fn test_only_idempotent_route_activates_the_boundary() {
        assert!(matches!(agreed(with_test_route), Activation::Active { .. }));
    }

    #[test]
    fn composing_the_test_route_adds_exactly_one_served_operation() {
        // The plain contract serves only what is composed into it: nothing,
        // so the boundary stays inactive, until an operation opts in.
        assert_eq!(
            served(&agreed(contract)) + 1,
            served(&agreed(with_test_route))
        );
    }
}
// template:end http-idempotency:service-api-idempotent-test-route
