//! CI-only proof that the pinned Go implementation and production Rust wire
//! boundary consume each other's records. The fixture is generated by the Go
//! bridge; this test neither implements a second Go encoder nor needs NATS.

use std::collections::BTreeMap;
use std::env;
use std::fs;

use async_nats::HeaderMap;
use base64::Engine as _;
use base64::engine::general_purpose::STANDARD;
use bytes::Bytes;
use domain_events::{Event, EventPayload};
use infra_messaging::wire::{
    CREATED_AT, DEAD_LETTER_REASON, DeadLetterRecord, NATS_MSG_ID, dead_letter_id, decode_envelope,
    encode_prepared, restore_dead_letter,
};
use infra_messaging::{Registry, Route};
use serde::Deserialize;
use time::OffsetDateTime;
use time::format_description::well_known::Rfc3339;

const FIXTURE_PATH_ENV: &str = "GO_WIRE_FIXTURES";
const EXPORT_PATH_ENV: &str = "GO_WIRE_RUST_EXPORT";
const MAX_PAYLOAD_BYTES: usize = 8 * 1024;

#[derive(Debug, Deserialize)]
struct FixtureSet {
    version: u8,
    cases: Vec<FixtureCase>,
}

#[derive(Debug, Deserialize)]
struct FixtureCase {
    name: String,
    inbound: WireRecord,
    decoded: DecodedRecord,
    reencoded: WireRecord,
    reencoded_go_decodes: bool,
    dlq: WireRecord,
    restored: EventRecord,
}

#[derive(Debug, Deserialize)]
struct EventRecord {
    subject: String,
    message_id: String,
    publication_id: String,
    event_type: String,
    schema: String,
    created_at: String,
    unix_seconds: i64,
    nanosecond: u32,
    body_base64: String,
}

#[derive(Debug, Deserialize, serde::Serialize)]
struct WireRecord {
    subject: String,
    headers: BTreeMap<String, String>,
    body_base64: String,
    stream: String,
    stream_sequence: u64,
    stored_at: String,
}

#[derive(Debug, Deserialize)]
struct DecodedRecord {
    subject: String,
    message_id: String,
    publication_id: String,
    event_type: String,
    schema: String,
    created_at: String,
    unix_seconds: i64,
    nanosecond: u32,
    body_base64: String,
}

#[derive(Debug, serde::Deserialize, serde::Serialize)]
struct BridgePayload {
    amount: f64,
    escaped: String,
    items: Vec<bool>,
}

impl EventPayload for BridgePayload {
    const EVENT_TYPE: &'static str = "example.created";
    const SCHEMA_VERSION: u16 = 1;
}

/// This scenario has one independent expectation: Go-produced raw bytes,
/// offsets, identities and transfer hashes remain consumable by the production
/// Rust boundary, while Go's real decoder accepts Rust's production bytes.
/// A Go wire drift or Rust normalization/identity regression fails here even
/// when either implementation's unit tests still pass in isolation.
#[test]
#[ignore = "CI generates GO_WIRE_FIXTURES with the pinned actual Go package"]
fn rust_production_wire_exports_for_go() {
    let fixtures = fixtures();
    assert_eq!(fixtures.version, 1, "unsupported Go-wire fixture version");
    for name in [
        "fractional_raw_bytes",
        "identity_schema_boundary",
        "go_permissive_fraction_offset",
        "go_offset_minute_sixty",
        "go_utc_year_boundary",
    ] {
        assert!(
            fixtures.cases.iter().any(|fixture| fixture.name == name),
            "fixture must retain the {name} actual-Go observation"
        );
    }

    for fixture in &fixtures.cases {
        verify_go_record_in_rust(fixture);
    }
    verify_production_limits(&fixtures);

    let records = rust_production_records();
    let export_path = env::var(EXPORT_PATH_ENV)
        .expect("CI must provide GO_WIRE_RUST_EXPORT for actual Go decode");
    fs::write(
        export_path,
        serde_json::to_vec_pretty(&records).expect("Rust records serialize"),
    )
    .expect("Rust production records write");
}

fn fixtures() -> FixtureSet {
    let path = env::var(FIXTURE_PATH_ENV)
        .expect("CI must generate GO_WIRE_FIXTURES before this test runs");
    serde_json::from_slice(&fs::read(path).expect("Go fixture reads"))
        .expect("Go fixture has the bridge record schema")
}

fn verify_go_record_in_rust(fixture: &FixtureCase) {
    let inbound_headers = headers(&fixture.inbound.headers);
    let inbound_body = body(&fixture.inbound.body_base64);
    let decoded = decode_envelope(
        &fixture.inbound.subject,
        &inbound_headers,
        inbound_body.clone(),
    )
    .unwrap_or_else(|error| panic!("{}: Go record rejected by Rust: {error}", fixture.name));

    assert_eq!(
        decoded.message_id(),
        fixture.decoded.message_id,
        "{} message ID",
        fixture.name
    );
    assert_eq!(
        decoded.event_type(),
        fixture.decoded.event_type,
        "{} event type",
        fixture.name
    );
    assert_eq!(
        decoded.schema_version(),
        schema_version(&fixture.decoded.schema),
        "{} schema",
        fixture.name
    );
    assert_eq!(
        decoded.occurred_at().unix_timestamp(),
        fixture.decoded.unix_seconds,
        "{} UTC seconds",
        fixture.name
    );
    assert_eq!(
        decoded.occurred_at().nanosecond(),
        fixture.decoded.nanosecond,
        "{} UTC nanoseconds",
        fixture.name
    );
    assert_eq!(
        decoded.payload().as_ref(),
        body(&fixture.decoded.body_base64).as_ref(),
        "{} raw payload",
        fixture.name
    );
    assert_eq!(
        fixture.inbound.subject, fixture.decoded.subject,
        "{} subject",
        fixture.name
    );
    assert_eq!(
        fixture.inbound.headers.get(NATS_MSG_ID),
        Some(&fixture.decoded.publication_id),
        "{} publication identity",
        fixture.name
    );

    assert_eq!(
        fixture.reencoded.headers.get(CREATED_AT),
        Some(&fixture.decoded.created_at),
        "{} Go re-emitted timestamp text",
        fixture.name
    );
    if fixture.reencoded_go_decodes {
        let reencoded = decode_envelope(
            &fixture.reencoded.subject,
            &headers(&fixture.reencoded.headers),
            body(&fixture.reencoded.body_base64),
        )
        .unwrap_or_else(|error| {
            panic!(
                "{}: Go-roundtrippable re-emission rejected by Rust: {error}",
                fixture.name
            )
        });
        assert_eq!(
            reencoded.occurred_at().unix_timestamp(),
            fixture.decoded.unix_seconds,
            "{} re-emitted UTC seconds",
            fixture.name
        );
        assert_eq!(
            reencoded.occurred_at().nanosecond(),
            fixture.decoded.nanosecond,
            "{} re-emitted UTC nanoseconds",
            fixture.name
        );
        assert_eq!(
            reencoded.payload().as_ref(),
            body(&fixture.decoded.body_base64).as_ref(),
            "{} re-emitted raw payload",
            fixture.name
        );
    }

    let source_publication_id = fixture
        .inbound
        .headers
        .get(NATS_MSG_ID)
        .expect("generated Go fixture has Nats-Msg-Id");
    let expected_transfer = dead_letter_id(
        &fixture.inbound.stream,
        fixture.inbound.stream_sequence,
        parse_timestamp(&fixture.inbound.stored_at),
        source_publication_id,
    )
    .unwrap_or_else(|error| panic!("{}: Rust DLQ id rejected Go source: {error}", fixture.name));
    assert_eq!(
        fixture.dlq.headers.get(NATS_MSG_ID),
        Some(&expected_transfer),
        "{} DLQ transfer hash",
        fixture.name
    );
    assert_eq!(
        fixture
            .dlq
            .headers
            .get(DEAD_LETTER_REASON)
            .map(String::as_str),
        Some("exhausted"),
        "{} DLQ reason",
        fixture.name
    );

    let restored = restore_dead_letter(DeadLetterRecord {
        subject: fixture.dlq.subject.clone(),
        headers: headers(&fixture.dlq.headers),
        payload: body(&fixture.dlq.body_base64),
        stream: fixture.dlq.stream.clone(),
        stream_sequence: fixture.dlq.stream_sequence,
        stored_at: parse_timestamp(&fixture.dlq.stored_at),
    })
    .unwrap_or_else(|error| panic!("{}: Go DLQ record rejected by Rust: {error}", fixture.name));
    assert_eq!(
        restored.subject(),
        fixture.restored.subject,
        "{} restored subject",
        fixture.name
    );
    assert_eq!(
        restored.message_id(),
        fixture.restored.message_id,
        "{} restored message ID",
        fixture.name
    );
    assert_eq!(
        restored.publication_id(),
        fixture.restored.publication_id,
        "{} redrive hash",
        fixture.name
    );
    assert_eq!(
        restored.event_type(),
        fixture.restored.event_type,
        "{} restored type",
        fixture.name
    );
    assert_eq!(
        restored.schema(),
        fixture.restored.schema,
        "{} restored schema",
        fixture.name
    );
    assert_eq!(
        restored.occurred_at().unix_timestamp(),
        fixture.restored.unix_seconds,
        "{} restored UTC seconds",
        fixture.name
    );
    assert_eq!(
        restored.occurred_at().nanosecond(),
        fixture.restored.nanosecond,
        "{} restored UTC nanoseconds",
        fixture.name
    );
    assert_eq!(
        fixture.restored.created_at, fixture.decoded.created_at,
        "{} Go-restored timestamp text",
        fixture.name
    );
    assert_eq!(
        restored.payload().as_ref(),
        body(&fixture.restored.body_base64).as_ref(),
        "{} restored raw payload",
        fixture.name
    );
}

fn verify_production_limits(fixtures: &FixtureSet) {
    let boundary = fixtures
        .cases
        .iter()
        .find(|fixture| fixture.name == "identity_schema_boundary")
        .expect("generated Go fixture retains identity/schema boundary");
    let decoded = decode_envelope(
        &boundary.inbound.subject,
        &headers(&boundary.inbound.headers),
        body(&boundary.inbound.body_base64),
    )
    .expect("Go's 256-byte identity and v65535 remain admitted");
    assert_eq!(decoded.message_id().len(), 256);
    assert_eq!(decoded.event_type().len(), 256);
    assert_eq!(decoded.schema_version(), u16::MAX);

    let event = bridge_event("x".repeat(257));
    assert!(
        event.is_err(),
        "over-limit Go identity must reject before encoding"
    );

    let registry = Registry::new([Route::new::<BridgePayload>("events.created")])
        .expect("bridge route admits");
    let event = bridge_event("rust-payload-limit").expect("bridge event admits");
    assert!(
        registry.prepare(&event, 1).is_err(),
        "production preparation enforces payload admission"
    );

    let mut oversized_headers = headers(&fixtures.cases[0].inbound.headers);
    oversized_headers.insert("X-Go-Wire-Limit", "x".repeat(MAX_PAYLOAD_BYTES));
    assert!(
        decode_envelope(
            &fixtures.cases[0].inbound.subject,
            &oversized_headers,
            body(&fixtures.cases[0].inbound.body_base64),
        )
        .is_err(),
        "production decoding enforces the 8 KiB header bound"
    );
}

fn rust_production_records() -> Vec<WireRecord> {
    let registry = Registry::new([Route::new::<BridgePayload>("events.rust")])
        .expect("Rust export route admits");
    let event = bridge_event("rust-go-compat-1").expect("Rust export event admits");
    let prepared = registry
        .prepare(&event, MAX_PAYLOAD_BYTES)
        .expect("production Rust preparation admits");
    let headers = encode_prepared(&prepared).expect("production Rust encoding admits");
    vec![WireRecord {
        subject: prepared.subject().to_owned(),
        headers: header_values(&headers),
        body_base64: STANDARD.encode(prepared.payload()),
        stream: "RUST_EXPORTS".to_owned(),
        stream_sequence: 1,
        stored_at: "2026-09-26T12:37:00.000000003Z".to_owned(),
    }]
}

fn bridge_event(id: impl Into<String>) -> Result<Event<BridgePayload>, domain_events::EventError> {
    Event::new(
        id,
        parse_timestamp("2026-09-26T12:34:56.123456789Z"),
        BridgePayload {
            amount: 1.0,
            escaped: "\\u0041".to_owned(),
            items: vec![true, false],
        },
    )
}

fn headers(values: &BTreeMap<String, String>) -> HeaderMap {
    let mut headers = HeaderMap::new();
    for (name, value) in values {
        headers.insert(name.as_str(), value.as_str());
    }
    headers
}

fn header_values(headers: &HeaderMap) -> BTreeMap<String, String> {
    headers
        .iter()
        .map(|(name, values)| {
            assert_eq!(
                values.len(),
                1,
                "production normal envelope has one value per header"
            );
            (name.to_string(), values[0].to_string())
        })
        .collect()
}

fn body(encoded: &str) -> Bytes {
    STANDARD
        .decode(encoded)
        .expect("fixture body is base64")
        .into()
}

fn parse_timestamp(value: &str) -> OffsetDateTime {
    OffsetDateTime::parse(value, &Rfc3339).expect("fixture timestamp is RFC3339")
}

fn schema_version(value: &str) -> u16 {
    value
        .strip_prefix('v')
        .expect("fixture schema begins with v")
        .parse()
        .expect("fixture schema has decimal version")
}
